//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:37:44 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Collaborator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ti.customer.schema;
